### ISSUE TITLE
Maquette HTML+CSS

### ISSUE THREAD

**Issue by yohanngab** [blank-project/project-maison-du-bas-belleville#4]

**Comment by MJB91** [comment]
**La page principale du site se présentera de la manière suivante :** 

- [ ] Haut de page : 
Sur la même ligne : Logo + input "abonnement newsletter" + liens rés.sociaux
Dessous : menu navigation : Qui sommes 
 _Suivre le fichier "arborescence site MBB.docx"_

- [ ] Banner : Slider avec annonce de l'évènement principal de l'année, puis deux éventuelles sur les activités de la MBB avec en lien "+ d'infos" sur le banner (button?)

- [ ] Widget Calendrier :  en Aside à droite de la page, semaine/ mois ? 
afficher les jours occupés en surbrillance, avec une action "on click" (au passage de la souris ou au clic ?) qui développerait un mini descriptif de l'évènement [titre event, age du public visé, heure, lieu, lien "+d'infos" (et "s'inscrire"?), en overflow. 

_Le lien "s'inscrire" mène à un formulaire d'adhésion si l'utilisateur n'est pas adhérent à l'asso ?
Vérification email.
Participation financiere à voir (paypal etc) ?

Revenir sur la page adhesion plus tard. (session utilisateur pour les adh? etc)_

- [ ] Main: Annonce des articles en quelques lignes, avec pour chaque article un lien "Plus d'infos"

- [ ] - Footer : Qui sommes nous ?/ Nos activités/ S'investir / Contacts

En dessous : banner avec les mentions légales.

**Comment by wawass** [comment]
[Squelette-site-a-modifier.tar.gz](https://github.com/blank-project/project-maison-du-bas-belleville/files/824526/Squelette-site-a-modifier.tar.gz)

**Comment by MJB91** [comment]
Nous utiliserons le framework Bootstrap pour le design du site. 
Edition charte graphique en cours : Codes couleurs, typos, tailles, etc.

**Comment by MJB91** [comment]
- [ ] Arborescence page index éditée. (+resp.)
- [ ] Autres pages éditées (HTML) avec les éléments de page initiaux.
- [ ] Framework bootstrap intégré à la page index et autres pages.
- [ ] heuuu
